apiVersion: v1
kind: Pod
metadata:
  name: streamlit-app
  labels:
    name: app
spec:
  containers:
    - name: streamlit-app
      image: menachemkazido/app:latest
      ports:
        - containerPort: 8501
